language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.3.0
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
env:
  - NONE=true
  - RAILS=true
  - RAILS=true MEMCACHE=true
matrix:
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails4.gemfile
script: "bundle exec rake spec"
sudo: false
cache: bundler
