language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
env:
  - NONE=true
  - RAILS=true
  - RAILS=true MEMCACHE=true
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails4.gemfile
script: "bundle exec rake coverage"
